#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    path: /
    defaults:
        route: admin_index

admin_index:
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    path: /admin
    defaults:
        template: 'index.html.twig'
